apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clientintents
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://github.com/vfiftyfive/oda-app-policies.git
      targetRevision: local
      path: clientintents
    - repoURL: https://github.com/vfiftyfive/oda-app-policies.git
      targetRevision: local
      path: game-service
  destination:
    server: https://kubernetes.default.svc
    namespace: oda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
