apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oda-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/vfiftyfive/otter-detective-agency.git
    targetRevision: local
    path: deploy/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: oda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
